In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy as np

### Numpy 기본 개념

In [6]:
## 1차원 데이터

test_array = np.array([1, 4, 5, 8], float) # 실수형으로

In [8]:
print(test_array)

[1. 4. 5. 8.]


In [10]:
print(test_array.dtype) # .dypte는 데이터 타입 출력

float64


In [12]:
print(test_array.shape) # .shape는 배열의 차원 구조 출력 (행 개수, 열 개수)

(4,)


In [14]:
## 2차원 데이터

test_matrix = [[1, 2, 5, 8], [1, 2, 4, 8], [1, 2, 5, 8]]
np.array(test_matrix, int).shape

(3, 4)

In [3]:
## 넘파이 데이터의 타입 변환
# 정수형을 float로 지정하면 모든 데이터가 정수형으로 저장되어, 소수점 데이터가 손실됨

np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [13]:
## 데이터 배열 변환

x = np.array([[1, 2,5 ,8], [1, 2, 5, 8]])

In [11]:
## flatten 데이터 그대로 1차원으로 변경

x = x.flatten()
print(x)

[1 2 5 8 1 2 5 8]


In [15]:
## reshape를 사용하면 전체 요소 개수 고려해서 마지막 차원이 자동으로 지정

x = x.reshape(2, -1)
print(x)

[[1 2 5 8]
 [1 2 5 8]]


In [17]:
## range
# 0부터 24까지 2씩 증가하는 numpy array

x = np.array(range(0, 25, 2))

In [19]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
# 24부터 0까지 2씩 감소하는 numpy array

x = np.array(range(24, -1, -2))

In [33]:
x

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [37]:
x = np.array(range(15))
x = x.reshape(3, -1) # 형태 변환
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [39]:
x[:, ::2] # 행 전체, 열은 2씩 증가하는 것만 가져오기

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [41]:
np.range(0, 5, 0.5) # 에러

AttributeError: module 'numpy' has no attribute 'range'

In [43]:
np.arange(0, 5, 0.5) # step에 소수 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [55]:
np.ones(shape = (5, 2), dtype = np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [59]:
np.zeros(shape = (2, 2), dtype = np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [61]:
np.empty(shape = (2, 4), dtype = np.float32)

array([[1.4e-45, 2.8e-45, 7.0e-45, 1.1e-44],
       [1.4e-45, 2.8e-45, 7.0e-45, 1.1e-44]], dtype=float32)

In [47]:
## 3x3 identity matrix
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
# 3x5 identity-like matrix
b = np.eye(3, 5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [63]:
c = np.eye(3, 5, 1) # 1을 우측으로 1씩 이동
print(c)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
